plugins:
  - jest

env:
  node: true
  jest: true
  es2020: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 2020

rules:
  no-console: 0
  import/no-named-as-default: error
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
